name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: print greeding
        run: echo " hellow world"
      - name: pring bye bye
        run: echo "good bye!"
        
  
